export const data = [
  {
    STT: "1",
    code: "49226071",
    name: "Trần Trung Bảo",
    DGDTX: [5, 7, 6, 6],
    DDGGK: "6.5",
    DDGCK: "5",
    TBM: "5.8",
    TBMCN: "5.7",
    review: "Nhận thức TB",
    reviewCN: "Nhận thức TB",
  },
  {
    STT: "2",
    code: "49226106",
    name: "Vũ Thị Ngọc Viên",
    DGDTX: [6, 6, 6, 5],
    DDGGK: "6.5",
    DDGCK: "6",
    TBM: "6",
    TBMCN: "6.4",
    review: "Nhận thức TB",
    reviewCN: "Nhận thức TB",
  },
  {
    STT: "3",
    code: "49226108",
    name: "Phạm Trần Kỳ Anh",
    DGDTX: [5, 6, 5, 5],
    DDGGK: "5.5",
    DDGCK: "5",
    TBM: "5.2",
    TBMCN: "5.2",
    review: "Nhận thức TB",
    reviewCN: "Nhận thức TB",
  },
  {
    STT: "4",
    code: "49226109",
    name: "Hoàng Thị Linh Chi",
    DGDTX: [7, 7, 6, 7],
    DDGGK: "8",
    DDGCK: "6",
    TBM: "6.8",
    TBMCN: "6.7",
    review: "Nhận thức Khá",
    reviewCN: "Nhận thức Khá",
  },
  {
    STT: "5",
    code: "49226111",
    name: "Vũ Đức Diện",
    DGDTX: [7, 7, 6, 6],
    DDGGK: "7",
    DDGCK: "6",
    TBM: "6.4",
    TBMCN: "6.4",
    review: "Nhận thức TB",
    reviewCN: "Nhận thức TB",
  },
  {
    STT: "6",
    code: "49226112",
    name: "Vũ Minh Dũng",
    DGDTX: [7, 9, 7, 8],
    DDGGK: "7",
    DDGCK: "7",
    TBM: "7.3",
    TBMCN: "7.2",
    review: "Nhận thức Khá",
    reviewCN: "Nhận thức Khá",
  },
  {
    STT: "7",
    code: "49226113",
    name: "Vũ Hải Đăng",
    DGDTX: [6, 6, 5, 6],
    DDGGK: "5",
    DDGCK: "5",
    TBM: "5.3",
    TBMCN: "5.6",
    review: "Nhận thức TB",
    reviewCN: "Nhận thức TB",
  },
  {
    STT: "8",
    code: "49226114",
    name: "Phạm Minh Đức",
    DGDTX: [5, 6, 5, 5],
    DDGGK: "6",
    DDGCK: "5",
    TBM: "5.3",
    TBMCN: "5.6",
    review: "Nhận thức TB",
    reviewCN: "Nhận thức TB",
  },
  {
    STT: "9",
    code: "49226115",
    name: "Phạm Thế Hải",
    DGDTX: [5, 6, 5, 5],
    DDGGK: "5",
    DDGCK: "5",
    TBM: "5.1",
    TBMCN: "5.1",
    review: "Nhận thức TB",
    reviewCN: "Nhận thức TB",
  },
  {
    STT: "10",
    code: "49226116",
    name: "Nguyễn Thị Bích Hạnh",
    DGDTX: [9, 9, 9.5, 9],
    DDGGK: "8",
    DDGCK: "9.5",
    TBM: "9",
    TBMCN: "9",
    review: "Nhận thức Tốt",
    reviewCN: "Nhận thức Tốt",
  },
  {
    STT: "11",
    code: "49226117",
    name: "Nguyễn Trung Hiếu",
    DGDTX: [7, 7, 7, 7],
    DDGGK: "7",
    DDGCK: "7",
    TBM: "7",
    TBMCN: "7.1",
    review: "Nhận thức Khá",
    reviewCN: "Nhận thức Khá",
  },
  {
    STT: "12",
    code: "49226118",
    name: "Phạm Minh Hiếu",
    DGDTX: [5, 6, 5, 5],
    DDGGK: "6.5",
    DDGCK: "5",
    TBM: "5.4",
    TBMCN: "5.3",
    review: "Nhận thức TB",
    reviewCN: "Nhận thức TB",
  },
  {
    STT: "13",
    code: "49226119",
    name: "Nguyễn Huy Hiệu",
    DGDTX: [6, 7, 6, 6],
    DDGGK: "7",
    DDGCK: "6",
    TBM: "6.3",
    TBMCN: "6.4",
    review: "Nhận thức TB",
    reviewCN: "Nhận thức TB",
  },
  {
    STT: "14",
    code: "49226120",
    name: "Vũ Gia Huy",
    DGDTX: [7, 7, 7, 8],
    DDGGK: "7",
    DDGCK: "7.5",
    TBM: "7.3",
    TBMCN: "7.1",
    review: "Nhận thức Khá",
    reviewCN: "Nhận thức Khá",
  },
  {
    STT: "15",
    code: "49226121",
    name: "Đặng Việt Hưng",
    DGDTX: [8, 7, 7, 7],
    DDGGK: "7",
    DDGCK: "7",
    TBM: "7.1",
    TBMCN: "7",
    review: "Nhận thức Khá",
    reviewCN: "Nhận thức Khá",
  },
  {
    STT: "16",
    code: "49226122",
    name: "Mai Tiến Hưng",
    DGDTX: [6, 7, 6, 6],
    DDGGK: "6",
    DDGCK: "6",
    TBM: "6.1",
    TBMCN: "6.3",
    review: "Nhận thức TB",
    reviewCN: "Nhận thức TB",
  },
  {
    STT: "17",
    code: "49226123",
    name: "Vũ Duy Khánh",
    DGDTX: [8, 8, 7, 8],
    DDGGK: "8.5",
    DDGCK: "8",
    TBM: "8",
    TBMCN: "8",
    review: "Nhận thức Khá",
    reviewCN: "Nhận thức Khá",
  },
  {
    STT: "18",
    code: "49226124",
    name: "Phan Thị Hương Lan",
    DGDTX: [9, 8, 8, 8],
    DDGGK: "7.5",
    DDGCK: "8",
    TBM: "8",
    TBMCN: "8.1",
    review: "Nhận thức Tốt",
    reviewCN: "Nhận thức Tốt",
  },
  {
    STT: "19",
    code: "49226125",
    name: "Phạm Kiều Linh",
    DGDTX: [6, 7, 6, 6],
    DDGGK: "6.5",
    DDGCK: "6",
    TBM: "6.2",
    TBMCN: "6.5",
    review: "Nhận thức Khá",
    reviewCN: "Nhận thức Khá",
  },
  {
    STT: "20",
    code: "49226126",
    name: "Trịnh Công Minh",
    DGDTX: [7, 7, 7, 7],
    DDGGK: "7",
    DDGCK: "8",
    TBM: "7.3",
    TBMCN: "7.4",
    review: "Nhận thức Khá",
    reviewCN: "Nhận thức Khá",
  },
  {
    STT: "21",
    code: "49226127",
    name: "Phan Trà My",
    DGDTX: [7, 7, 6, 7],
    DDGGK: "7.5",
    DDGCK: "7",
    TBM: "7",
    TBMCN: "7.5",
    review: "Nhận thức Tốt",
    reviewCN: "Nhận thức Tốt",
  },
  {
    STT: "22",
    code: "49226128",
    name: "Nguyễn Thị Trà My",
    DGDTX: [9, 8, 8, 8],
    DDGGK: "8",
    DDGCK: "8",
    TBM: "8.1",
    TBMCN: "8",
    review: "Nhận thức Khá",
    reviewCN: "Nhận thức Khá",
  },
  {
    STT: "23",
    code: "49226129",
    name: "Vũ Ánh Ngọc",
    DGDTX: [8, 8, 8, 8],
    DDGGK: "8",
    DDGCK: "8",
    TBM: "8",
    TBMCN: "8",
    review: "Nhận thức Tốt",
    reviewCN: "Nhận thức Tốt",
  },
  {
    STT: "24",
    code: "49226130",
    name: "Phạm Nguyễn Tuyết Nhung",
    DGDTX: [9, 8, 8, 8],
    DDGGK: "7.5",
    DDGCK: "8.5",
    TBM: "8.2",
    TBMCN: "8.1",
    review: "Nhận thức Tốt",
    reviewCN: "Nhận thức Tốt",
  },
  {
    STT: "25",
    code: "49226131",
    name: "Trần Gia Phát",
    DGDTX: [9, 9, 9, 9.5],
    DDGGK: "8",
    DDGCK: "9.5",
    TBM: "9",
    TBMCN: "9",
    review: "Nhận thức Tốt",
    reviewCN: "Nhận thức Tốt",
  },
  {
    STT: "26",
    code: "49226132",
    name: "Phan Minh Quân",
    DGDTX: [5, 6, 5, 6],
    DDGGK: "6",
    DDGCK: "5",
    TBM: "5.4",
    TBMCN: "5.3",
    review: "Nhận thức TB",
    reviewCN: "Nhận thức TB",
  },
  {
    STT: "27",
    code: "49226134",
    name: "Nguyễn Hữu Tất Thành",
    DGDTX: [7, 8, 7, 7],
    DDGGK: "7.5",
    DDGCK: "7",
    TBM: "7.2",
    TBMCN: "7.4",
    review: "Nhận thức Khá",
    reviewCN: "Nhận thức Khá",
  },
  {
    STT: "28",
    code: "49226135",
    name: "Nguyễn Thanh Thư",
    DGDTX: [3, 4, 2, 2],
    DDGGK: "5.5",
    DDGCK: "1.5",
    TBM: "2.9",
    TBMCN: "4",
    review: "Nhận thức Yếu",
    reviewCN: "Nhận thức Yếu",
  },
  {
    STT: "29",
    code: "49226136",
    name: "Nguyễn Mạnh Tiến",
    DGDTX: [9, 8, 8, 8],
    DDGGK: "7",
    DDGCK: "7",
    TBM: "7.6",
    TBMCN: "7.6",
    review: "Nhận thức Khá",
    reviewCN: "Nhận thức Khá",
  },
  {
    STT: "30",
    code: "49226137",
    name: "Vũ Minh Tiến",
    DGDTX: [8, 9, 8, 8],
    DDGGK: "7",
    DDGCK: "8.5",
    TBM: "8.1",
    TBMCN: "8",
    review: "Nhận thức Tốt",
    reviewCN: "Nhận thức Tốt",
  },
  {
    STT: "31",
    code: "49226138",
    name: "Nguyễn Minh Tiệp",
    DGDTX: [8, 8, 7, 6],
    DDGGK: "8",
    DDGCK: "7",
    TBM: "7.3",
    TBMCN: "7.2",
    review: "Nhận thức Khá",
    reviewCN: "Nhận thức Khá",
  },
  {
    STT: "32",
    code: "49226140",
    name: "Trần Thị Mai Trang",
    DGDTX: [8, 8, 7, 8],
    DDGGK: "7.5",
    DDGCK: "7",
    TBM: "7.4",
    TBMCN: "7.6",
    review: "Nhận thức Khá",
    reviewCN: "Nhận thức Khá",
  },
  {
    STT: "33",
    code: "49226141",
    name: "Nguyễn Thị Thùy Trâm",
    DGDTX: [9, 9, 8, 8],
    DDGGK: "8",
    DDGCK: "8",
    TBM: "8.2",
    TBMCN: "8.3",
    review: "Nhận thức Tốt",
    reviewCN: "Nhận thức Tốt",
  },
  {
    STT: "34",
    code: "49226142",
    name: "Nguyễn Thị Ánh Tuyết",
    DGDTX: [7, 7, 7, 7],
    DDGGK: "7",
    DDGCK: "7",
    TBM: "7",
    TBMCN: "7.1",
    review: "Nhận thức Khá",
    reviewCN: "Nhận thức Khá",
  },
  {
    STT: "35",
    code: "49226143",
    name: "Nguyễn Thị Khánh Uyên",
    DGDTX: [6, 7, 6, 6],
    DDGGK: "6",
    DDGCK: "6",
    TBM: "6.1",
    TBMCN: "6.2",
    review: "Nhận thức TB",
    reviewCN: "Nhận thức TB",
  },
  {
    STT: "36",
    code: "49226144",
    name: "Vũ Đức Vinh",
    DGDTX: [6, 7, 6, 7],
    DDGGK: "6",
    DDGCK: "6",
    TBM: "6.2",
    TBMCN: "6.2",
    review: "Nhận thức TB",
    reviewCN: "Nhận thức TB",
  },
  {
    STT: "37",
    code: "49226145",
    name: "Trần Phương Vy",
    DGDTX: [9, 9, 8, 8],
    DDGGK: "8",
    DDGCK: "8.5",
    TBM: "8.4",
    TBMCN: "8.5",
    review: "Nhận thức Tốt",
    reviewCN: "Nhận thức Tốt",
  },
  {
    STT: "38",
    code: "49226146",
    name: "Trần Thảo Vy",
    DGDTX: [8, 8, 7, 7],
    DDGGK: "8",
    DDGCK: "7",
    TBM: "7.4",
    TBMCN: "7.5",
    review: "Nhận thức Khá",
    reviewCN: "Nhận thức Khá",
  },
  {
    STT: "39",
    code: "49226147",
    name: "Nguyễn Thị Tường Vy",
    DGDTX: [7, 7, 7, 8],
    DDGGK: "6.5",
    DDGCK: "7.5",
    TBM: "7.2",
    TBMCN: "6.9",
    review: "Nhận thức Khá",
    reviewCN: "Nhận thức Khá",
  },
  {
    STT: "40",
    code: "48143201",
    name: "Lê Quỳnh Như",
    DGDTX: [9, 9, 8, 8],
    DDGGK: "8.5",
    DDGCK: "8",
    TBM: "8.3",
    TBMCN: "8.4",
    review: "Lực học bộ môn ở mức khá, cần phát huy hơn nữa trong học tập",
    reviewCN:
      "Năng động, tích cực trong học tập. Siêng năng, nhiệt tình trong các hoạt động học tập. Kết quả học tập khá.",
  },
];
