export const summaryStudentScore2 = [
  {
    STT: "1",
    name: "Đồng Bảo Anh",
    id: "49547411",
    literature: "8.1",
    math: "8.5",
    english: "7.9",
    physics: "7.9",
    civics: "8.3",
    chemistry: "7.9",
    biology: "8.3",
    history: "8",
    technology: "8.3",
    geography: "8.5",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "8.2",
    academic_performance: "Giỏi",
    conduct: "Tốt",
    rank: "6",
  },
  {
    STT: "2",
    name: "Nguyễn Thị Ngọc Ánh",
    id: "49547412",
    literature: "7.1",
    math: "6.6",
    english: "6.6",
    physics: "7.4",
    civics: "7.9",
    chemistry: "7.3",
    biology: "7.4",
    history: "6.8",
    technology: "7.3",
    geography: "7.6",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "7.2",
    academic_performance: "Khá",
    conduct: "Tốt",
    rank: "14",
  },
  {
    STT: "3",
    name: "Nguyễn Đức Bảo",
    id: "49547413",
    literature: "7",
    math: "7.3",
    english: "5.6",
    physics: "7.5",
    civics: "6.9",
    chemistry: "5.7",
    biology: "6.1",
    history: "6.4",
    technology: "8",
    geography: "6.9",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "6.8",
    academic_performance: "Khá",
    conduct: "Khá",
    rank: "20",
  },
  {
    STT: "4",
    name: "Phạm Thế Bảo",
    id: "49547414",
    literature: "5.4",
    math: "4.7",
    english: "4.7",
    physics: "5.6",
    civics: "6.6",
    chemistry: "5.4",
    biology: "5.5",
    history: "6.4",
    technology: "6.6",
    geography: "7.4",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "5.8",
    academic_performance: "Trung bình",
    conduct: "Tốt",
    rank: "34",
  },
  {
    STT: "5",
    name: "Nguyễn Quang Chung",
    id: "49547416",
    literature: "7",
    math: "7.3",
    english: "6",
    physics: "6",
    civics: "7.3",
    chemistry: "6.5",
    biology: "6.9",
    history: "6.4",
    technology: "7.7",
    geography: "7.1",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "6.8",
    academic_performance: "Khá",
    conduct: "Tốt",
    rank: "20",
  },
  {
    STT: "6",
    name: "Bùi Thế Công",
    id: "49547417",
    literature: "6.2",
    math: "6.4",
    english: "5.4",
    physics: "5.9",
    civics: "6.7",
    chemistry: "6.3",
    biology: "6.3",
    history: "6.5",
    technology: "7.4",
    geography: "6.9",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "6.4",
    academic_performance: "Trung bình",
    conduct: "Tốt",
    rank: "28",
  },
  {
    STT: "7",
    name: "Bùi Nguyễn Quốc Cường",
    id: "49547418",
    literature: "6.1",
    math: "5.4",
    english: "5.8",
    physics: "5.1",
    civics: "6.9",
    chemistry: "5.3",
    biology: "5.6",
    history: "6",
    technology: "7",
    geography: "6.4",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "6",
    academic_performance: "Trung bình",
    conduct: "Tốt",
    rank: "33",
  },
  {
    STT: "8",
    name: "Trần Thị Phương Diễm",
    id: "49547419",
    literature: "7",
    math: "6.6",
    english: "5.9",
    physics: "7.1",
    civics: "7.7",
    chemistry: "7.8",
    biology: "7.5",
    history: "7.1",
    technology: "7.3",
    geography: "7.1",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "7.1",
    academic_performance: "Khá",
    conduct: "Tốt",
    rank: "17",
  },
  {
    STT: "9",
    name: "Bùi Văn Dũng",
    id: "49547420",
    literature: "7",
    math: "9",
    english: "7.2",
    physics: "7.3",
    civics: "7.7",
    chemistry: "7.3",
    biology: "7.2",
    history: "6.8",
    technology: "9.2",
    geography: "7.6",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "7.7",
    academic_performance: "Khá",
    conduct: "Tốt",
    rank: "10",
  },
  {
    STT: "10",
    name: "Vũ Văn Đại",
    id: "49547421",
    literature: "6.6",
    math: "6.7",
    english: "5.6",
    physics: "7",
    civics: "7.4",
    chemistry: "6.4",
    biology: "6.4",
    history: "7.6",
    technology: "7.5",
    geography: "7.3",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "6.9",
    academic_performance: "Khá",
    conduct: "Tốt",
    rank: "19",
  },
  {
    STT: "11",
    name: "Nguyễn Trà Giang",
    id: "49547422",
    literature: "7",
    math: "5.7",
    english: "5.8",
    physics: "7.3",
    civics: "7.6",
    chemistry: "7.5",
    biology: "7.6",
    history: "7.6",
    technology: "7",
    geography: "7.1",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "7",
    academic_performance: "Khá",
    conduct: "Tốt",
    rank: "18",
  },
  {
    STT: "12",
    name: "Nguyễn Mai Thái Hà",
    id: "49547423",
    literature: "6.3",
    math: "6.8",
    english: "5.4",
    physics: "5.5",
    civics: "6.9",
    chemistry: "5.6",
    biology: "6",
    history: "6",
    technology: "7.4",
    geography: "6.3",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "6.3",
    academic_performance: "Trung bình",
    conduct: "Tốt",
    rank: "31",
  },
  {
    STT: "13",
    name: "Đỗ Thị Hạnh",
    id: "49547424",
    literature: "7.3",
    math: "7.2",
    english: "6.6",
    physics: "7.3",
    civics: "8",
    chemistry: "8.1",
    biology: "7.8",
    history: "7.1",
    technology: "7.4",
    geography: "6.4",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "7.3",
    academic_performance: "Khá",
    conduct: "Tốt",
    rank: "13",
  },
  {
    STT: "14",
    name: "Nguyễn Thị Thu Hằng",
    id: "49547425",
    literature: "8.1",
    math: "7.5",
    english: "7.6",
    physics: "8.1",
    civics: "8.3",
    chemistry: "8.6",
    biology: "8.6",
    history: "7.8",
    technology: "8",
    geography: "8.3",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "8.1",
    academic_performance: "Giỏi",
    conduct: "Tốt",
    rank: "8",
  },
  {
    STT: "15",
    name: "Trần Trung Hiếu",
    id: "49547426",
    literature: "7",
    math: "8.4",
    english: "6.2",
    physics: "7.3",
    civics: "7.7",
    chemistry: "6.9",
    biology: "7.3",
    history: "6.9",
    technology: "8.4",
    geography: "6.2",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "7.2",
    academic_performance: "Khá",
    conduct: "Tốt",
    rank: "14",
  },
  {
    STT: "16",
    name: "Đinh Quang Huy",
    id: "49547427",
    literature: "7",
    math: "7.3",
    english: "6.4",
    physics: "6.8",
    civics: "7.4",
    chemistry: "5.5",
    biology: "5.6",
    history: "6.5",
    technology: "8.2",
    geography: "7.3",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "6.8",
    academic_performance: "Khá",
    conduct: "Tốt",
    rank: "20",
  },
  {
    STT: "17",
    name: "Vũ Tuấn Hưng",
    id: "49547428",
    literature: "5.4",
    math: "5.3",
    english: "5.3",
    physics: "5.5",
    civics: "6",
    chemistry: "5.3",
    biology: "5.1",
    history: "5.9",
    technology: "7.1",
    geography: "5.8",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "5.7",
    academic_performance: "Trung bình",
    conduct: "Tốt",
    rank: "35",
  },
  {
    STT: "18",
    name: "Vũ Phương Linh",
    id: "49547429",
    literature: "8.5",
    math: "8.2",
    english: "9.2",
    physics: "8.4",
    civics: "9",
    chemistry: "7.6",
    biology: "8.1",
    history: "8.3",
    technology: "8.9",
    geography: "8.6",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "8.5",
    academic_performance: "Giỏi",
    conduct: "Tốt",
    rank: "3",
  },
  {
    STT: "19",
    name: "Phan Công Nguyên",
    id: "49547431",
    literature: "6.1",
    math: "4.8",
    english: "4.9",
    physics: "7.3",
    civics: "7.1",
    chemistry: "5.5",
    biology: "6.3",
    history: "6.4",
    technology: "6.8",
    geography: "6.9",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "6.2",
    academic_performance: "Trung bình",
    conduct: "Tốt",
    rank: "32",
  },
  {
    STT: "20",
    name: "Trịnh Sỹ Nguyên",
    id: "49547432",
    literature: "5.4",
    math: "5.1",
    english: "4.4",
    physics: "5.5",
    civics: "5.7",
    chemistry: "5.1",
    biology: "5.3",
    history: "5.3",
    technology: "6.8",
    geography: "5.9",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "5.5",
    academic_performance: "Trung bình",
    conduct: "Khá",
    rank: "36",
  },
  {
    STT: "21",
    name: "Vũ Tiến Phong",
    id: "49547433",
    literature: "7.2",
    math: "8.2",
    english: "6.6",
    physics: "7.6",
    civics: "8",
    chemistry: "8",
    biology: "7.9",
    history: "7.1",
    technology: "8.4",
    geography: "8.2",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "7.7",
    academic_performance: "Khá",
    conduct: "Tốt",
    rank: "10",
  },
  {
    STT: "22",
    name: "Trần Minh Quân",
    id: "49547434",
    literature: "6.9",
    math: "6",
    english: "5.4",
    physics: "6.4",
    civics: "7.3",
    chemistry: "7",
    biology: "6.5",
    history: "7.5",
    technology: "7.4",
    geography: "6.6",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "6.7",
    academic_performance: "Khá",
    conduct: "Tốt",
    rank: "25",
  },
  {
    STT: "23",
    name: "Vũ Thị Thanh Tâm",
    id: "49547435",
    literature: "8.2",
    math: "8.6",
    english: "8.3",
    physics: "8.6",
    civics: "9",
    chemistry: "7.9",
    biology: "8.8",
    history: "8.1",
    technology: "9.1",
    geography: "9.1",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "8.6",
    academic_performance: "Giỏi",
    conduct: "Tốt",
    rank: "2",
  },
  {
    STT: "24",
    name: "Phạm Thanh Thảo",
    id: "49547436",
    literature: "8.6",
    math: "8.6",
    english: "8.2",
    physics: "8.8",
    civics: "9.1",
    chemistry: "8",
    biology: "8.1",
    history: "8.1",
    technology: "9",
    geography: "8.9",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "8.5",
    academic_performance: "Giỏi",
    conduct: "Tốt",
    rank: "3",
  },
  {
    STT: "25",
    name: "Nguyễn Văn Thiên",
    id: "49547437",
    literature: "6.3",
    math: "7.3",
    english: "6.3",
    physics: "7.4",
    civics: "6.7",
    chemistry: "6.1",
    biology: "6.6",
    history: "5.9",
    technology: "7.6",
    geography: "7.3",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "6.8",
    academic_performance: "Khá",
    conduct: "Tốt",
    rank: "20",
  },
  {
    STT: "26",
    name: "Nguyễn Văn Thiện",
    id: "49547438",
    literature: "6.8",
    math: "7.1",
    english: "5.7",
    physics: "7",
    civics: "6.9",
    chemistry: "6.1",
    biology: "6.3",
    history: "6.5",
    technology: "7.6",
    geography: "6.8",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "6.7",
    academic_performance: "Khá",
    conduct: "Tốt",
    rank: "25",
  },
  {
    STT: "27",
    name: "Tống Đức Thịnh",
    id: "49547439",
    literature: "5",
    math: "4.7",
    english: "4.4",
    physics: "5.8",
    civics: "5.7",
    chemistry: "5.3",
    biology: "5.4",
    history: "6",
    technology: "6.8",
    geography: "6.3",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "5.5",
    academic_performance: "Trung bình",
    conduct: "Khá",
    rank: "36",
  },
  {
    STT: "28",
    name: "Bùi Minh Thuân",
    id: "49547440",
    literature: "7",
    math: "7.3",
    english: "5.7",
    physics: "6.5",
    civics: "7.3",
    chemistry: "5.9",
    biology: "5.9",
    history: "6.8",
    technology: "7.7",
    geography: "7.7",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "6.8",
    academic_performance: "Khá",
    conduct: "Tốt",
    rank: "20",
  },
  {
    STT: "29",
    name: "Phạm Thị Thúy",
    id: "49547441",
    literature: "8.3",
    math: "9.2",
    english: "9.3",
    physics: "9.6",
    civics: "9.1",
    chemistry: "8.9",
    biology: "9",
    history: "8.4",
    technology: "9.2",
    geography: "8.8",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "9",
    academic_performance: "Giỏi",
    conduct: "Tốt",
    rank: "1",
  },
  {
    STT: "30",
    name: "Thạch Thị Anh Thư",
    id: "49547442",
    literature: "6.3",
    math: "6",
    english: "5.3",
    physics: "6.8",
    civics: "7.1",
    chemistry: "6.1",
    biology: "6.5",
    history: "5.9",
    technology: "7.4",
    geography: "6.4",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "6.4",
    academic_performance: "Trung bình",
    conduct: "Tốt",
    rank: "28",
  },
  {
    STT: "31",
    name: "Vũ Thị Anh Thư",
    id: "49547443",
    literature: "7.2",
    math: "6.5",
    english: "6.3",
    physics: "6.9",
    civics: "8",
    chemistry: "7.1",
    biology: "7.6",
    history: "7",
    technology: "7.6",
    geography: "6.9",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "7.2",
    academic_performance: "Khá",
    conduct: "Tốt",
    rank: "14",
  },
  {
    STT: "32",
    name: "Kim Quang Trung",
    id: "49547444",
    literature: "8.3",
    math: "8.3",
    english: "8",
    physics: "8.4",
    civics: "8.7",
    chemistry: "7.1",
    biology: "7.8",
    history: "8",
    technology: "9",
    geography: "8.4",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "8.1",
    academic_performance: "Giỏi",
    conduct: "Tốt",
    rank: "8",
  },
  {
    STT: "33",
    name: "Nguyễn Đức Trung",
    id: "49547445",
    literature: "6.9",
    math: "8.3",
    english: "6.2",
    physics: "7.6",
    civics: "7.9",
    chemistry: "7.9",
    biology: "8.1",
    history: "6.3",
    technology: "8",
    geography: "6.4",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "7.4",
    academic_performance: "Khá",
    conduct: "Tốt",
    rank: "12",
  },
  {
    STT: "34",
    name: "Phạm Công Trưởng",
    id: "49547446",
    literature: "6.9",
    math: "6.9",
    english: "6.1",
    physics: "6.6",
    civics: "7.3",
    chemistry: "6.1",
    biology: "6.4",
    history: "6.3",
    technology: "7.5",
    geography: "6.4",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "6.7",
    academic_performance: "Khá",
    conduct: "Tốt",
    rank: "25",
  },
  {
    STT: "35",
    name: "Nguyễn Thị Bảo Uyên",
    id: "49547448",
    literature: "8.2",
    math: "8.3",
    english: "7.9",
    physics: "8",
    civics: "8.7",
    chemistry: "8.4",
    biology: "8.3",
    history: "7.2",
    technology: "8.9",
    geography: "8.3",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "8.2",
    academic_performance: "Giỏi",
    conduct: "Tốt",
    rank: "6",
  },
  {
    STT: "36",
    name: "Đỗ Thị Uyên",
    id: "49547449",
    literature: "7.6",
    math: "8.6",
    english: "8.4",
    physics: "9.4",
    civics: "8.7",
    chemistry: "8.1",
    biology: "8.4",
    history: "7.8",
    technology: "8.9",
    geography: "8.3",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "8.4",
    academic_performance: "Giỏi",
    conduct: "Tốt",
    rank: "5",
  },
  {
    STT: "37",
    name: "Nguyễn Ngọc Thảo Vi",
    id: "49547450",
    literature: "6.4",
    math: "5.9",
    english: "5.2",
    physics: "6.9",
    civics: "7.1",
    chemistry: "5.9",
    biology: "6.4",
    history: "6.4",
    technology: "7.2",
    geography: "6.9",
    physical_education: "Đ",
    music: "",
    art: "Đ",
    GPA: "6.4",
    academic_performance: "Trung bình",
    conduct: "Tốt",
    rank: "28",
  },
];
